### ISSUE TITLE
As a User I should be able to Add a Todo List Item

### ISSUE THREAD

**Issue by celopez3-wcci** [celopez3-wcci/Fall-2021-Courses-Workshop#4]
Front End:

User should have a way to create a new todo item

Back End:

API Endpoint for HTTPPost

**Comment by celopez3-wcci** [comment]
- [ ] Created API Endpoint for HTTPPost

- [ ] Added HTML Element to link for Create
- [ ] Added Fetch for HTTPPost
